services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: neo-postgres

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_HOST_BIND}:${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 15s

    networks:
      - neo-network

    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: neo-pgadmin

    env_file:
      - .env

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

      PGADMIN_CONFIG_SERVER_MODE: "True"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"

      PGADMIN_DISABLE_POSTFIX: "True"

    ports:
      - "${PGADMIN_HOST_BIND}:${PGADMIN_PORT}:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - neo-network

    restart: unless-stopped

volumes:
  postgres_data:
    name: ${NETWORK_NAME}_postgres_data

  pgadmin_data:
    name: ${NETWORK_NAME}_pgadmin_data

networks:
  neo-network:
    external: true
    name: ${NETWORK_NAME}