"""add workflow tracking fields

Revision ID: 32b05bd65709
Revises: 
Create Date: 2026-05-17 16:41:42.004956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b05bd65709'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requisitions', sa.Column('return_reason', sa.Text(), nullable=True))
    op.add_column('requisitions', sa.Column('returned_to_indentor', sa.Boolean(), nullable=True))
    op.add_column('requisitions', sa.Column('assigned_to_procurement', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requisitions', 'assigned_to_procurement')
    op.drop_column('requisitions', 'returned_to_indentor')
    op.drop_column('requisitions', 'return_reason')
    # ### end Alembic commands ###
